"""Wrapper for testing with jest
"""

# load("@npm//jest:index.bzl", _jest_test = "jest_test")
load("@npm//jest-cli:index.bzl", _jest_test = "jest_test")

def jest_test(name, srcs, config_file, deps = [], **kwargs):
    """A macro around the autogenerated jest test rule
    Args:
        name: name
        srcs: srcs
        config_file: config_file
        deps: deps
        **kwargs: **kwargs
    """
    args = [
        "--no-cache",
        "--no-watchman",
        "--ci",
        "--colors",
    ]
    args.extend(["--config", "$(location %s)" % config_file])
    for src in srcs:
        args.extend(["--runTestsByPath", "$(location %s)" % src])

    data = ["@npm//@types/jest", "@npm//ts-jest"]
    data.extend(srcs)
    data.extend(deps)
    data.extend([config_file])

    _jest_test(
        name = name,
        data = data,
        args = args,
        **kwargs
    )
