name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.2.0'
          cache: 'npm'
          cache-dependency-path: typescript/package-lock.json

      - name: Install leetkick globally
        run: npm install -g leetkick

      - name: Install TypeScript dependencies
        run: |
          cd typescript
          npm ci

      - name: Setup C++ build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++

      - name: Run TypeScript tests
        run: leetkick test --language typescript

      - name: Run C++ tests
        run: leetkick test --language cpp
