name: ci

on: push

jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: 'macos-latest'
    name: test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup deno
        uses: denolib/setup-deno@v1.3.0
      - name: Run tests
        run: deno test
